const CONSTANTS = {
  LEFT: 90, //z
  RIGHT: 88, //x
  FIRE: 32, //space
  LOOP_INTERVAL_MILLIS: 20,
  PLAYER_SPEED: 20,
  SHOT_SPEED: 10,
  PLAYER_RADIUS: 40,
  SHOT_LIMIT: 50,
  SHOT_POSITION_QUANTIZATION: 20,
  SCREEN_WIDTH: 720,
  SHOT_HEIGHT: 20,
  BAD_GUY_DELAY: 50
};

export default CONSTANTS;
