]const CONSTANTS = {
  LEFT: 90, //z
  RIGHT: 88, //x
  FIRE: 16, //shift
  PAUSE: 32, // space
  LOOP_INTERVAL_MILLIS: 20,
  PLAYER_SPEED: 10,
  SHOT_SPEED: 10,
  PLAYER_RADIUS: 40,
  SHOT_LIMIT: 50,
  SHOT_POSITION_QUANTIZATION: 20,
  SCREEN_WIDTH: 720,
  SHOT_HEIGHT: 20,
  BAD_GUY_DELAY: 30,
  BAD_GUY_PLACEHOLDERS: [0,1,2,3,4,5,6,7,8]
};

export default CONSTANTS;
