const CONSTANTS = {
  LEFT: 90, //z
  RIGHT: 88, //x
  FIRE: 32, //space
  LOOP_INTERVAL_MILLIS: 20,
  PLAYER_SPEED: 20,
  SHOT_SPEED: 10,
  PLAYER_RADIUS: 30,
  SHOT_LIMIT: 50,
  SHOT_POSITION_QUANTIZATION: 20,
  SCREEN_WIDTH: 1074,
  SHOT_HEIGHT: 20
};

export default CONSTANTS;
